### ISSUE TITLE
Codecov token exposed in .travis.yml

### ISSUE THREAD

**Issue by redfast00** [padreati/rapaio#142]
Hi, your codecov token seems to be exposed in the `.travis.yml` file. This could lead to malicious people uploading false reports.

**Comment by padreati** [comment]
Thank you for noticing that. Honestly, I really do not know how to handle that, I am totally new to codecov travis and stuff, mostly concentrated on the coding part. Do you have a suggestion regarding that? (At least until I read and found myself a solution?). Best regards.

**Comment by redfast00** [comment]
I just worked with codecov for the first time myself. According to the docs, `codecov` on a Travis CI server should work. Don't forget to get another token for this repo after you changed the command.

**Comment by padreati** [comment]
I regenerated another token in order to avoid access from outside. However, for public projects, the access is handled differently, and the token is not needed. The token is required for private repositories or other custom access.
