### ISSUE TITLE
New version of SMO

### ISSUE THREAD

**Issue by selcukyazartr** [padreati/rapaio#166]
Hi, where can i find a new version of this ? http://rapaio.blogspot.com/2015/01/

regards.

**Comment by padreati** [comment]
Hi. I am not sure about your question. Do you expect a new version of SMO? I do not remember to have it. There is a version of BinarySMO in rapaio.ml.classifier.svm. It is not thoroughly tested, but as far as I am concerned it works.

**Comment by selcukyazartr** [comment]
Hi , thank you for reply. In your blog,
i think "color(new Color(0f, 0f, 1f, (float) pp[i + 1])))" property of MeshContour doesn't exist in newer version. I'm not good at java so maybe you have a new version of sample tutorial of code about SVM and SMO. 

Anyway, this is great job. Thank you again.

Best regards.

**Comment by padreati** [comment]
I have to rework the api for meshes, but I did not had enough time (I am mostly alone and there is a huge effort to do everything well at production level). It will be done properly, for sure, I do not know when.
However I translated that piece of code without simplifications, and adapted to the current version of library:

`package blog;

import rapaio.core.*;
import rapaio.core.stat.*;
import rapaio.data.Frame;
import rapaio.data.*;
import rapaio.experiment.grid.*;
import rapaio.graphics.plot.*;
import rapaio.ml.classifier.*;
import rapaio.ml.classifier.svm.*;
import rapaio.ml.classifier.svm.kernel.*;
import rapaio.ml.eval.*;
import rapaio.sys.*;

import java.awt.*;

import static rapaio.graphics.Plotter.*;

/**
 * Created by <a href="mailto:padreati@yahoo.com">Aurelian Tutuianu</a> on 1/8/19.
 */
public class MeshContourTest {

    public static void main(String[] args) {
        // build the data set

        RandomSource.setSeed(1);

        Var v1 = VarDouble.empty().withName("x");
        Var v2 = VarDouble.empty().withName("y");
        Var v3 = VarNominal.empty().withName("class");

        for (int i = 0; i < 4; i++) {
            for (int j = 0; j < 4; j++) {
                for (int k = 0; k < 100; k++) {
                    v1.addDouble(RandomSource.nextDouble() + i);
                    v2.addDouble(RandomSource.nextDouble() + j);
                    v3.addLabel((i + j) % 2 == 0 ? "True" : "False");
                }
            }
        }

        Frame df = SolidFrame.byVars(v1, v2, v3);

        // build classifier

        Classifier c = new BinarySMO().withKernel(new WaveletKernel(0.55)).withC(0.1);
        c.fit(df, "class");

        Confusion.from(df.rvar("class"), c.predict(df).firstClasses()).summary();

        // new build the mesh grid

        Var x = VarDouble.seq(Minimum.of(df.rvar(0)).value() - 1, Maximum.of(df.rvar(0)).value() + 1, 0.05).withName("x");
        Var y = VarDouble.seq(Minimum.of(df.rvar(1)).value() - 1, Maximum.of(df.rvar(1)).value() + 1, 0.05).withName("y");


        MeshGrid1D mg = new MeshGrid1D(x, y);

        Var x1 = VarDouble.empty().withName("x");
        Var y1 = VarDouble.empty().withName("y");

        for (int i = 0; i < x.rowCount(); i++) {
            for (int j = 0; j < y.rowCount(); j++) {
                x1.addDouble(x.getDouble(i));
                y1.addDouble(y.getDouble(j));
            }
        }

        // fit the mesh grid values

        Frame grid = SolidFrame.byVars(x1, y1);
        CPrediction cr = c.predict(grid, true, true);

        int pos = 0;
        for (int i = 0; i < x.rowCount(); i++) {
            for (int j = 0; j < y.rowCount(); j++) {
                mg.setValue(i, j, cr.firstDensity().getDouble(pos, 1) - cr.firstDensity().getDouble(pos, 2));
                pos++;
            }
        }

        // and finally plot the results

        Plot p = new Plot();
        double[] pp = new double[]{0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.8, 1};
        double[] qq = mg.quantiles(pp);

        for (int i = 0; i < qq.length - 1; i++) {
            p.meshContour(mg.compute(qq[i], qq[i + 1]), false, true, color(new Color(0f, 0f, 1f, (float) pp[i + 1])));
        }
        p.meshContour(mg.compute(0, Double.POSITIVE_INFINITY), true, false, color(0), lwd(2f));

        WS.draw(p.points(df.rvar(0), df.rvar(1), color(df.rvar(2))), 800, 600);

    }
}
`

**Comment by padreati** [comment]
Those tutorials will be refactored in notebook fashion anyway

**Comment by selcukyazartr** [comment]
thank you for your help. :)
