### ISSUE TITLE
Plot markers ignore number format settings defined in user locale.

### ISSUE THREAD

**Issue by iromeo** [padreati/rapaio#170]
Plot markers ignore number format settings defined in user locale. E.g. for RU or FR locale I get "0.7" instead of "0,7". 

To reproduce set the locale to non-us, e.g. add VM options
-Duser.language=ru
-Duser.country=RU

**Comment by iromeo** [comment]
The discussion started in #167

**Comment by padreati** [comment]
I fixed with last commit. However I am still not content with it. I would like to use scientific notation for very large numbers but I do not know how to display it locale specific. Do you have any idea?

**Comment by iromeo** [comment]
I think you can use `String.format(..)` for Locale aware scientific and normal notations, e.g

```
String.format("%.5e", 0.4599838383838383838383838383e-11) --> 4,59984e-12
String.format("%.3e", 0.4599838383838383838383838383e-11) ---> 4,600e-12

String.format("%.5f", 0.4599838383838383838383838383e-11) --> 0,00000
String.format("%.5f", 0.4) --> 0,40000
```
or use DecimalFormat to remove trailing zeros from fraction part
```
new DecimalFormat("#.#####").format(0.4) -> 0,4 
new DecimalFormat("#.###E0").format(0.4599838383838383838383838383e-11) -> 4,6E-12
new DecimalFormat("#.#####E0").format(0.4599838383838383838383838383e-11) -> 4,59984E-12
```

**Comment by padreati** [comment]
I will leave it like it is now until I found a better solution. The issue itself its is not exactly how to display using locale specific, but when to decide to use scientific notation and when to use decimal notation. This problem is in itself related with XWilkinson algorithm and not to formatting
