### ISSUE TITLE
solve the bar chart problem with negative numbers

### ISSUE THREAD

**Issue by padreati** [padreati/rapaio#42]
when plotting negative values into a bar chart the negative numbers are omitted and the drawing is wrong. it should be displayed below 0

**Comment by VishwaasHegde** [comment]
The BarChart class seems to be deprecated, what is the alternative for it?

**Comment by padreati** [comment]
There is no alternative to it, it should be fixed. It is marked as deprecated in order to signal that it has some problems. I did not found other way to signal that.

**Comment by padreati** [comment]
Now it was fixed. It also was improved, the documentation needs updated with it.
